version: '3'

volumes:
  vscode_ssh: {}

services:
  app_vscode:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    working_dir: /home/node/app
    volumes:
      - ../../:/home/node/app
      - vscode_ssh:/root/.ssh
    env_file:
      - app/.env
    environment:
      - DOCKER_SERVER=true
    command:
      - /bin/sh
      - -c
      - |
        npm install
        sleep infinity
    networks:
      - external_network
    ports:
      - "8100:8100"

networks:
  external_network:
    external:
      name: frontendexercise-network

